unit needs .-escaping when job is unstaged.

diff --git a/bin/deployer-queue b/bin/deployer-queue
--- a/bin/deployer-queue
+++ b/bin/deployer-queue
@@ -1,18 +1,28 @@
 #!/bin/sh
 
-. shellsafe || { echo "error sourcing shellsafe." 1>&2 ; exit 100 ; }
+main()
+{
+  safe test -n "$DEPLOYER_QUEUE"
+  safe cd "$DEPLOYER_QUEUE"
 
-safe test -n "$DEPLOYER_QUEUE"
-safe cd "$DEPLOYER_QUEUE"
+  # Move deploy job files from the per-unit request directories into processing.
 
-# Move deploy job files from the per-unit request directories into processing.
+  safe find req -mindepth 2 -maxdepth 2 -type f | {
+    IFS=/
+    while read req unit file; do
+      unit_escaped=`job_escape "$unit"`
+      safe mv "req/${unit}/${file}" "new/${unit_escaped}.${file}"
+    done
+  }
 
-safe find req -mindepth 2 -maxdepth 2 -type f | {
-  IFS=/
-  while read req unit file; do
-    safe mv "req/${unit}/${file}" "new/${unit}.${file}"
-  done
+  exec fsq-run -v -Q new -D cur -A deployer-after-job . deployer-worker
 }
 
-exec fsq-run -v -Q new -D cur -A deployer-after-job . deployer-worker
+job_escape() {
+  printf "%s" "$1" | sed -e 's/%/%26/g; s/\//%2f/g; s/\./%2e/g'
+}
+
+. shellsafe || { echo "error sourcing shellsafe." 1>&2 ; exit 100 ; }
+main "$@"
+exit $?
 
