new "bottom half" privsep script + ssh keying, priv dropping.

diff --git a/bin/deployer b/bin/deployer
--- a/bin/deployer
+++ b/bin/deployer
@@ -31,119 +31,51 @@ main()
   test ! -d "${DEPLOYER_DATA_DIR}/${unit}" && barf "unit is unmanaged: ${unit}"
 
   # Self-exec to put per-unit settings in environment, unless we've already done that.
+  # FIXME don't let 99 under self-exec be loud failure
 
-  test "$unit" = "$DEPLOYER_UNIT" || safe envdir "${DEPLOYER_DATA_DIR}/${unit}" "$0" "$unit" "$revision" "$@"
+  test "$unit" = "$DEPLOYER_UNIT" || safe exec envdir "${DEPLOYER_DATA_DIR}/${unit}" "$0" "$unit" "$revision" "$@"
 
-  # Require existing .a & .b directories, unless we're in update-in-place mode (.x).
+  # In privileged mode, these per-unit settings are required.
 
-  deploy_root="$DEPLOYER_DEPLOY_ROOT"
-  path_a="${deploy_root}/${unit}.a"
-  path_b="${deploy_root}/${unit}.b"
-  path_x="${deploy_root}/${unit}.x"
-
-  if [ -d "$path_x" ]; then
-    target_default="${unit}.x"
-  else
-    target_default="${unit}.a"
-    test -d "$path_a" || barf "missing git checkout: $path_a"
-    test -d "$path_b" || barf "missing git checkout: $path_b"
+  if [ `id -u` -eq 0 ]; then
+    test -z "$DEPLOYER_USER"  && barf "missing required per-unit setting in privileged mode: DEPLOYER_USER"
+    test -z "$DEPLOYER_GROUP" && barf "missing required per-unit setting in privileged mode: DEPLOYER_GROUP"
   fi
 
-  # Determine the currently active checkout for this unit.
-  # Create the initial symlink if necessary.
+  # Load any per-unit ssh-key and make it available.
+  # FIXME don't let 99 under self-exec be loud failure
 
-  path_symlink="${deploy_root}/${unit}"
-
-  test -L "$path_symlink" || safe ln -s "$target_default" "$path_symlink"
-
-  if [ -L "$path_symlink" ]; then
-    target_old=`readlink "$path_symlink"`
-  elif [ -e "$path_symlink" ]; then
-    barf "non-symlink at: $path_symlink"
-  else
-    barf "failed to find symlink at: $path_symlink"
+  if [ -n "$DEPLOYER_SSH_KEY" ]; then
+    test -n "$SSH_AUTH_SOCK" || safe exec ssh-agent "$0" "$unit" "$revision" "$@"
+    safe ssh-add "$DEPLOYER_SSH_KEY"
+    if [ `id -u` -eq 0 ]; then
+      safe chmod g+w "$SSH_AUTH_SOCK"
+      safe chgrp "$DEPLOYER_GROUP" "$SSH_AUTH_SOCK"
+    fi
   fi
 
-  # Determine the currently inactive checkout for this unit.
+  # Run the "bottom half" of this operation. Drop privileges in privileged mode.
 
-  if [ "$target_default" = "${unit}.x" ]; then
-    target_new="${unit}.x"
-  elif [ "$target_old" = "${unit}.a" ]; then
-    target_new="${unit}.b"
-  else
-    target_new="${unit}.a"
-  fi
+  export DEPLOYER_UNIT
+  export DEPLOYER_REVISION="$revision"
 
-  path_old="${deploy_root}/${target_old}"
-  path_new="${deploy_root}/${target_new}"
-
-  # Determine the currently active branch and revision.
-
-  export GIT_WORK_TREE="$path_old"
-  export GIT_DIR="${path_old}/.git"
-  revision_old=`safe git rev-parse HEAD`
-  test -n "$revision_old" || barf "error getting current revision for: ${target_old}"
-  branch_old=`git symbolic-ref HEAD 2>/dev/null`
-  branch_old=${branch_old##refs/heads/}
-
-  # If revision is _, try to stay on same branch as active checkout.
-
-  if [ "$revision" = "_" ]; then
-    revision="$branch_old"
-    test -n "$revision" || barf "error defaulting to active branch: detached checkout?"
-  fi
-
-  # Update the inactive checkout with git.
-
-  export GIT_WORK_TREE="$path_new"
-  export GIT_DIR="${path_new}/.git"
-  safe git fetch
-
-  # See if the inactive checkout would differ from the active one.
-
-  differs=0
-  if [ "x"`git cat-file -t "$revision_old" 2>/dev/null` != "xcommit" ]; then
-    # This commit might not even exist anymore (eg was deleted in force push).
-    differs=1
-  else
-    git diff --quiet "$revision_old" origin/"$revision"
+  if [ `id -u` -eq 0 ]; then
+    target_new=`setuidgid -s "$DEPLOYER_USER" deployer-update "$@"`
     rc=$?
-    case $rc in
-      0|1) differs="$rc" ;;
-      *) barf "git-diff failed with exit code: $rc" ;;
-    esac
+  else
+    target_new=`deployer-update "$@"`
+    rc=$?
   fi
-
-  # Exit with special status if it would be identical to the active checkout.
-
-  if [ "$differs" -eq 0 ]; then
-    log 2 "no changes for: ${target_new} ${revision}"
-    exit 99
-  fi
-
-  # XXX workaround: git-stash doesn't honor GIT_WORK_TREE / GIT_DIR as of 1.9.1
-  log 2 "applying changes to inactive checkout: ${target_new}"
-  ( safe cd "$GIT_WORK_TREE" && git stash )
-  safe git checkout -B "$revision" origin/"$revision"
-
-  # Run the tail program (typically just `make`) to do post-update tasks.
-  # Touch a file to indicate that a new deployment happened.
-
-  (
-    safe cd "$path_new"
-    test $# -eq 0 || safe "$@"
-    safe touch .deployed
-  )
-  rc="$?" ; if [ "$rc" -ne 0 ]; then return "$rc"; fi
+  test $rc -eq 0 || exit $rc
 
   # Create the new symlink under the .tmp/ dir.
 
-  safe ln -s "$target_new" "${deploy_root}/.tmp/${unit}"
+  safe ln -s "$target_new" "${DEPLOYER_DEPLOY_ROOT}/.tmp/${unit}"
 
   # Atomically move the new symlink into place.
 
   (
-    safe cd "${deploy_root}/.tmp"
+    safe cd "${DEPLOYER_DEPLOY_ROOT}/.tmp"
     safe mv "$unit" ..
   )
   rc="$?" ; if [ "$rc" -ne 0 ]; then return "$rc"; fi
